Repository xEdziu/RPG-Handy-Helper, pull requests merged in 2025-06, with the labels that each got.

#258 [FRONT] Lobby gier
  .github/workflows/pr-check.yml
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpghandyhelper/chat/ChatController.java
  src/main/java/dev/goral/rpghandyhelper/chat/ChatMessage.java
  src/main/java/dev/goral/rpghandyhelper/game/GameRepository.java
  src/main/java/dev/goral/rpghandyhelper/game/GameService.java
  src/main/java/dev/goral/rpghandyhelper/game/gameUsers/GameUsersRepository.java
  src/main/java/dev/goral/rpghandyhelper/scheduler/service/SchedulerService.java
  src/main/java/dev/goral/rpghandyhelper/user/UserController.java
  src/main/java/dev/goral/rpghandyhelper/user/UserService.java
  src/main/resources/static/img/assets/chat-dice-icon-dark-version.svg
  src/main/resources/static/img/assets/chat-dice-icon-light-version.svg
  src/main/resources/static/room.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/auth/register.html
  src/main/resources/templates/home/profile.html
Labels: frontend

#270 Cp red character enemies
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpghandyhelper/game/gameUsers/GameUsersRepository.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/CpRedCharactersRepository.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterEnemies/CpRedCharacterEnemiesController.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterEnemies/CpRedCharacterEnemiesRepository.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterEnemies/CpRedCharacterEnemiesRequest.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterEnemies/CpRedCharacterEnemiesService.java
Labels: backend

#275 [FRONTEND] Ankiety na czacie
  src/main/java/dev/goral/rpghandyhelper/chat/PollController.java
  src/main/resources/static/room.html
Labels: frontend

#291 Implement null handling for character user when removing a user
  src/main/java/dev/goral/rpghandyhelper/game/GameService.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/CpRedCharactersRepository.java
Labels: backend

#296 CpRedCharacterWeapon
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomWeapon/CpRedCharacterCustomWeapon.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomWeapon/CpRedCharacterCustomWeaponDTO.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterWeapon/AddCharacterWeaponRequest.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterWeapon/CpRedCharacterWeapon.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterWeapon/CpRedCharacterWeaponController.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterWeapon/CpRedCharacterWeaponDTO.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterWeapon/CpRedCharacterWeaponHandType.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterWeapon/CpRedCharacterWeaponRepository.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterWeapon/CpRedCharacterWeaponService.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterWeapon/UpdateCharacterWeaponRequest.java
Labels: backend, task, java

#295 293 backend cpredcharacterfriends
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterFriends/CpRedCharacterFriendsController.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterFriends/CpRedCharacterFriendsRepository.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterFriends/CpRedCharacterFriendsRequest.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterFriends/CpRedCharacterFriendsService.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterTragicLoveStory/CpRedCharacterTragicLoveStoryService.java
Labels: backend

#315 CpRedCharacterCustomArmor
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomArmor/AddCharacterCustomArmorRequest.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomArmor/CpRedCharacterCustomArmor.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomArmor/CpRedCharacterCustomArmorController.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomArmor/CpRedCharacterCustomArmorDTO.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomArmor/CpRedCharacterCustomArmorRepository.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomArmor/CpRedCharacterCustomArmorService.java
  src/main/java/dev/goral/rpghandyhelper/rpgSystems/cpRed/characters/characterCustomArmor/UpdateCharacterCustomArmorRequest.java
Labels: backend
