Repository xEdziu/RPG-Handy-Helper, pull requests merged in 2025-05, with the labels that each got.

#119 Zapomnialem hasla
  src/main/resources/templates/auth/forgotPassword.html
Labels: frontend

#161 Naprawa zmiany nicku po logowaniu discordem
  src/main/java/dev/goral/rpgmanager/security/CustomOAuth2UserService.java
Labels: bug

#124 Service/controller dla cp red calsses
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/classes/CpRedClassesController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/classes/CpRedClassesRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/classes/CpRedClassesService.java
Labels: backend

#143 Service/controller dla cp red armors
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/armors/CpRedArmorsController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/armors/CpRedArmorsService.java
Labels: backend

#165 Service/controller dla cp red cyberwares
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/cyberwares/CpRedCyberwaresControler.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/cyberwares/CpRedCyberwaresRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/cyberwares/CpRedCyberwaresService.java
Labels: backend

#174 Service/controller dla cp red equipments
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/game/Game.java
  src/main/java/dev/goral/rpgmanager/game/GameService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/characters/CpRedCharactersService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/equipments/CpRedEquipmentsController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/equipments/CpRedEquipmentsRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/equipments/CpRedEquipmentsService.java
Labels: backend

#187 Service/controller dla cp red custom armors
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customArmors/CpRedCustomArmors.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customArmors/CpRedCustomArmorsController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customArmors/CpRedCustomArmorsDTO.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customArmors/CpRedCustomArmorsRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customArmors/CpRedCustomArmorsRequest.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customArmors/CpRedCustomArmorsService.java
Labels: backend

#189 Service/controller dla cp red critical injuries
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/criticalInjuries/CpRedCriticalInjuriesController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/criticalInjuries/CpRedCriticalInjuriesRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/criticalInjuries/CpRedCriticalInjuriesService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/cyberwares/CpRedCyberwaresService.java
Labels: backend

#191 Service/controller dla cp red custom critical injuries
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCriticalInjuries/CpRedCustomCriticalInjuriesController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCriticalInjuries/CpRedCustomCriticalInjuriesRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCriticalInjuries/CpRedCustomCriticalInjuriesRequest.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCriticalInjuries/CpRedCustomCriticalInjuriesService.java
Labels: backend

#194 Service/controller dla cp red custom cyberwares
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customArmors/CpRedCustomArmorsService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCyberwares/CpRedCustomCyberwaresController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCyberwares/CpRedCustomCyberwaresRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCyberwares/CpRedCustomCyberwaresRequest.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCyberwares/CpRedCustomCyberwaresService.java
Labels: backend

#204 Service/controller dla cp red custom equipments
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCyberwares/CpRedCustomCyberwaresService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customEquipments/CpRedCustomEquipmentsController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customEquipments/CpRedCustomEquipmentsRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customEquipments/CpRedCustomEquipmentsRequest.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customEquipments/CpRedCustomEquipmentsService.java
Labels: backend

#251 Bug przypisanie innego gameId do customowego obiektu
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customAmmunition/CpRedCustomAmmunitionService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customArmors/CpRedCustomArmorsService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCriticalInjuries/CpRedCustomCriticalInjuriesService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customCyberwares/CpRedCustomCyberwaresService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customEquipments/CpRedCustomEquipmentsService.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/custom/customWeapons/CpRedCustomWeaponsService.java
Labels: backend

#236 Backend servicecontroller dla CpRedWeaponMods
  .idea/JetClient/state.xml
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/weaponMods/CpRedWeaponModsController.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/weaponMods/CpRedWeaponModsRepository.java
  src/main/java/dev/goral/rpgmanager/rpgSystems/cpRed/manual/weaponMods/CpRedWeaponModsService.java
Labels: backend
